# Site
name: "Peneliti Onlien"
title: "Peneliti Onlien"
description: "Berbagi Informasi Onlien Yang Mendidik"
logo: 'assets/images/logo1.png'
favicon: 'assets/images/favicon.ico'
baseurl: ""
google_analytics: ''
disqus: 'postkomik-github-1'

include: ["_pages"]
permalink: /:title/
email: Ahmadalwy@gmail.com

# Authors
authors:
  
    
  postkomik:
    name: Postkomik
    display_name: Postkomik
    avatar: 'assets/images/avatar.png'
    email: Ahmadalwy@gmail.com
    web: https://penelitionlien.github.io/
    twitter: https://twitter.com/AlwiMubagas
    description: "Author of postkomik, a Manga Mahua styled template available for Blogger, HTML, . You are currently previewing Website."
    
  

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""
adsense-data-ad-format: ""
# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"




# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

#exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
