backend:
  name: github
  repo: penelitionlien/penelitionlien.github.io
  branch: main
publish_mode: editorial_workflow
media_folder: "assets/images/uploads"

collections:
  - name: "posts"
    label: "Post"
    folder: "_posts"
    filter:
      field: language
      value: en
    fields:
      - {label: "Language", name: "language"}
